app/models.py
from enum import Enum as PythonEnum

from sqlalchemy import Column, Integer, String, DateTime, Enum
from sqlalchemy.ext.declarative import declarative_base

from app import db

Base = declarative_base()


class GameStatus(PythonEnum):
    blackout = "Blacked Out"
    auth_failure = "Authentication Failed (retrying..)"
    waiting = "Waiting to download"
    downloading = "Downloading"
    decoding = "Decoding video"
    skip_silence = "Removing commercial breaks"
    obfuscating = "Obfuscating video end"
    moving = "Moving to final destination"
    completed = "Completed"


class DbGame(Base):
    __tablename__ = "games"
    id = Column(Integer, primary_key=True)
    home_team = Column(String(250))
    away_team = Column(String(250))
    time = Column(DateTime)
    status = Column(Enum(GameStatus), nullable=False)
    current_operation_progress = Column(Integer)
    game_info = Column(String(250))
    download_attempts = Column(Integer)
    download_start = Column(DateTime)
    download_end = Column(DateTime)
    next_attempt = Column(DateTime)

app/__init__.py
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config

bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bootstrap.init_app(app)

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)
    from app import models

    return app

app/main/__init__.py
from flask import Blueprint
bp = Blueprint('main', __name__)
from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for
from app import db
from app.models import DbGame, GameStatus
from app.main import bp


@bp.route("/")
def index():
    return render_template("index.html")


@bp.route("/ajax")
def ajax():
    data = db.session.query(DbGame).order_by(DbGame.time.desc()).limit(10)
    return render_template("ajax.html", games=data, GameStatus=GameStatus)

app/templates/ajax.html
<ul class="list-group">
  {% for game in games %}
  <li class="list-group-item">
    <p>{{ game.time }}</p>
    <h5 class="bigga">{{ game.home_team }} vs. {{ game.away_team }} </h5>
    {% if game.status == GameStatus.completed %}
    <h5 class="bigga"><span class="label label-success">Completed</span> <span class="minitext pull-right">Downloaded in {{(game.download_end - game.download_start).seconds // 60}} minutes</span></h5>
    {% else %}
    <h5 class="bigga"><span class="label label-info">{{ game.status.value }}</span></h5>
    {% endif %}
    {% if game.status == GameStatus.downloading %}
    <br />
    <br />
    <div class="progress">
      <div
        class="progress-bar progress-bar-striped active"
        role="progressbar"
        aria-valuenow="{{ game.current_operation_progress }}"
        aria-valuemin="0"
        aria-valuemax="100"
        style="width: {{ game.current_operation_progress }}%;"
      >
        <span class="sr-only"
          >{{ game.current_operation_progress }}% Complete</span
        >
      </div>
    </div>
    {% endif %} {% endfor %}
  </li>
</ul>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
<link href="{{url_for('static', filename='main.css')}}" rel="stylesheet"></link>
{{super()}}
{% endblock %}
{% block title %}
NHLTV
{% endblock %}


{% block content %}
<div class="container ">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}
{% endwith %}
{% block app_content %}

{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block app_content %}
<a class="hidden ajaxurl" id="ajaxurl" href="{{url_for('main.ajax')}}">/ajax</a>

  <div class="col-md-12">
    <div class="row">
      <p class="lastupdate pull-left"></p>
    </div>
    <div class="row status">
    </div>
    <div class="row">
    </div>
  </div>

<script>
  var url = $('.ajaxurl').attr('href');
  function getData() {
    $.get({
      url: $('.ajaxurl').attr('href'),
      type: 'get',
      success: function (data) {
        $('.status').html(data);
      }
    });
  };
  getData();
  setInterval(getData, 60000);
</script>
{% endblock %}